### PR TITLE
Final project submision

### PR DESCRIPTION
**Pull request by naikd0**
I was actually able to fix the dates but long story short I accidentally deleted the app.R file, is there a way you could help me restore the most updated version?

### CODE REVIEW

**Comment by sjspielman** [comment]
The command you want to use is probably `git checkout`, as detailed here: http://htmlpreview.github.io/?https://github.com/sjspielman/datascience_for_biologists/blob/master/materials/github_cheatsheet.html

Seems like you deleted the file locally but you didn't delete the file from github. If you want to keep working on this until Tuesday with this info let me know - otherwise I will consider this the submission. Respond to a comment here ASAP with preference!

**Comment by naikd0** [comment]
Thank you for your help I was able to recover my file, thinking it over I
will delete the fork and submit the updated files

**Comment by naikd0** [comment]
How do I fork the final again?

Dowd Naik

**Comment by sjspielman** [comment]
Forking means getting your own version of the repository - you have already forked it so you should not fork again. You need to checkout your missing files with `git checkout FILENAME`. Please see the class resources for more info on using git - that's the most I can help with this sort of issue at this late stage.

**Comment by naikd0** [comment]
I thought I had to delete the fork so I did now I cannot refork it, my
apologies I thought I was following instructions.  Is there another way I
could submit the project?

Dowd Naik

**Comment by naikd0** [comment]
If I have cause any problems I truly apologize

**Pull request merged**
